[E 2024-12-24 08:46:38,284 C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'ip: 123.194.176.32 not allow.', 'ip_address': '123.194.176.32', 'person_id': 'D122948227', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
